# Generated by Django 5.0.1 on 2024-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_1_id', models.CharField(max_length=30)),
                ('par_1_gen', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_2_id', models.CharField(max_length=30)),
                ('par_2_gen', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
