# Generated by Django 5.0.1 on 2024-01-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parent_1_parent_2_delete_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent_2',
        ),
    ]
