# Generated by Django 5.0.1 on 2024-01-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plant_delete_parent_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Hybridization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hybrid_name', models.CharField(max_length=255)),
                ('parent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to='main.plant')),
                ('parent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent2', to='main.plant')),
            ],
        ),
    ]
