# Generated by Django 5.0.1 on 2024-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_hybridization_hybrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cold_resistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plant',
            name='drought_resistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plant',
            name='heat_resistance',
            field=models.FloatField(default=0.0),
        ),
    ]
