# Generated by Django 5.0.1 on 2024-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_plant_cold_resistance_plant_drought_resistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='cold_resistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='drought_resistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='heat_resistance',
            field=models.FloatField(default=0.0),
        ),
    ]
