# Generated by Django 5.0.1 on 2024-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hybrid_cold_resistance_hybrid_drought_resistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cold_resistance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='drought_resistance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plant',
            name='heat_resistance',
            field=models.IntegerField(),
        ),
    ]
