# Generated by Django 5.0.1 on 2024-03-01 04:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='id',
            field=models.CharField(default=main.models.generate_random_id, editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
