# Generated by Django 5.0.1 on 2024-03-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_hybrid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='description',
            new_name='plant_description',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plant_name',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='cold_resistance',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='drought_resistance',
        ),
        migrations.RemoveField(
            model_name='hybrid',
            name='heat_resistance',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='cold_resistance',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='drought_resistance',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='heat_resistance',
        ),
    ]
