# Generated by Django 5.0.1 on 2024-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_description_plant_plant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='tree_growth_type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='tree_height',
            field=models.IntegerField(default=0),
        ),
    ]
