# Generated by Django 5.0.1 on 2024-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_plant_anthocyanin_coloration_degree_of_fruit_abscission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='anthocyanin_coloration_degree_of_fruit_abscission',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='bark_oiliness',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='bark_russeting',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='branch_lenticels_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='branch_puffiness',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='calyx_contraction',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='calyx_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='calyx_rust',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='calyx_size',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='consumption_readiness',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='dominant_color_before_blooming',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='flesh_color',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='flesh_density',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='flower_arrangement',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='flower_diameter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='flowering_onset',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_base_shape',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_diameter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_groove',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_length_diameter_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_side_rust',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_size',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_surface_color_area',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_surface_color_coverage',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_surface_color_intensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='fruit_surface_color_tone',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='groove_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='groove_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='harvest_readiness',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='interleaf_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_condition',
            field=models.CharField(default='Healthy', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_green_intensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_length_width_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_margin_serration',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_under_surface_puffiness',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='leaf_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pedicel_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pedicel_pit_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pedicel_pit_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='pedicel_thickness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='petiole_anthocyanin_coloration',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='petiole_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='plant_description',
            field=models.TextField(default='Coming soon', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='seed_chamber_opening',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='single_year_stem_thickness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='stamen_position_relative_to_pistils',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='stripe_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='sun_side_color',
            field=models.CharField(default='Green', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='tree_fruit_production',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='tree_growth_type',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='tree_habit',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='tree_height',
            field=models.IntegerField(default=0),
        ),
    ]
