# Generated by Django 5.0.1 on 2024-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_hybrid_anthocyanin_coloration_degree_of_fruit_abscission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_hybrid',
            field=models.BooleanField(default=False),
        ),
    ]
