# Generated by Django 5.0.1 on 2024-04-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_plant_is_hybrid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='is_hybrid',
        ),
    ]
