# Generated by Django 5.0.1 on 2024-04-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_plant_is_hybrid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybrid',
            name='plant_description',
        ),
        migrations.AddField(
            model_name='hybrid',
            name='hybrid_description',
            field=models.TextField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='parent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent1_set', to='main.plant'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='parent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent2_set', to='main.plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_description',
            field=models.TextField(default='Not Specified', max_length=255),
        ),
    ]
