# Generated by Django 5.0.1 on 2024-06-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_hybrid_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent1_hybrids', to='main.plant'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent2_hybrids', to='main.plant'),
        ),
    ]
